spring.application.name=CCSOP
server.port=8080
# user test
spring.security.user.name=admin
spring.security.user.password=secret123
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always